name: Main Draft

on:
  pull_request:
    types: [closed]

permissions:
  contents: write

jobs:
  update_main_draft:
    if: ${{ github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Update Main Release Draft
        uses: release-drafter/release-drafter@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          config-name: .github/release-drafter-main.yml
          publish: false
