name: Publish Release

on:
  pull_request:
    types: [closed, labeled]

permissions:
  contents: write

jobs:
  publish_release:
    if: ${{ github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'Publish') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Select Config File
        id: config
        run: |
          if [ "${{ github.event.pull_request.base.ref }}" == "develop" ]; then
            echo "config=.github/release-drafter-develop.yml" >> $GITHUB_OUTPUT
          else
            echo "config=.github/release-drafter-main.yml" >> $GITHUB_OUTPUT
          fi

      - name: Publish Release Draft
        uses: release-drafter/release-drafter@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          config-name: ${{ steps.config.outputs.config }}
          publish: true
